export const usersActionTypes = {

    SEARCH_REQUEST: 'SEARCH_REQUEST',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILED: 'SEARCH_FAILED',

    //Ambil data
    GET_INFORMASIABSENSI_REQUEST: 'GET_INFORMASIABSENSI_REQUEST',
    GET_INFORMASIABSENSI_SUCCESS: 'GET_INFORMASIABSENSI_SUCCES',
    GET_INFORMASIABSENSI_FAILED: 'GET_INFORMASIABSENSI_FAILED',


    //get
    GET_IPK_REQUEST: 'GET_IPK_REQUEST',
    GET_IPK_SUCCESS: 'GET_IPK_SUCCES',
    GET_IPK_FAILED: 'GET_IPK_FAILED',

    // Tambahkan action types



}